### PR TITLE
Enabling user to control encoding options

### PR DESCRIPTION
**Pull request by oganm**
This is meant to document what are the issues with encoding and what the solutions are in this pull request. Most of this includes less important details. See **bolded** notes for important stuff

Unusual characters can cause `set_fields` and `get_fields` options to experience problems. Examples of such characters are Ñ, ñ, É, Í, Ó ½ ¾ → ‘ ’ ” “ •.

The first step in PDF form filling is to dump the data fields. This is done using `dump_data_fields` command through pdftk, within the `get_fields` function. Unusual characters are not a problem
in this step because they are written as numeric character references. We resolve these characters after reading the file using the `sub_decimal` function. 

However field names in this file are encoded differently. In these cases something similar to but not quite unicode seems to be used. Some examples are ½ which appears as #C2#BD while it would have been 00BD in unicode, ¾ which appears as #C2#BE while it would have been 00BE in unicode and → which appears as #E2#86#92 but would have been 2192 in unicode. There is probably a pattern there but I haven't been able to understand it. This however doesn't seem to cause any issues because this encoding it preserved across the this file and the FDF file we will use to actually do the filling. My current solution is to leave them as is and nothing will be broken. This is problematic if a future fix arrives though as these fields will almost certainly be referred by their names. So if a fix is possible, I better find it quickly. **Note: This is a part where I will ask for some external help. We can live without this fix but currently, anyone who uses entirely "unusual" characters (chinese, japanese, arabic, russian, greek...) only sees weird combinations of letters, numbers and octothorps on field names which I imagine significantly reduces usability**

Next step is to generate an FDF file and read it. FDF files are necesary because they are what is accepted by `pdftk` to fill the fields. This operation is performed twice during the pdf filling process. First within the `get_fields` function where it is used to ensure field names in dump_fields are indeed fillable. Essentially if a field name in dumped fields don't appear on this file, it cannot be filled. As stated before, field names themselves are not an issue in this process. Not reading this file by `latin1` will always trigger a warning when parsing by `fdfAnnotate`. This is because second line of the FDF file is always "%âãÏÓ". The way we read this file is unimportant as field names don't have issues and the content will be overwritten by what we get from the `dump_data_fields` option using `fdfEdit` function. Important parts are whether or not reading is successful and does writing produce the desired output. Note that regardless of the encoding choice, when reading some characters seem to be inferred as nulls, cutting lines for field information in half. For instance a field, pre-filled with ½ ¾ `→ ‘ ’ ” “ •` gets cut of in both UTF-8 and latin1 encodings. Currently the detection of fields do not rely on seeing a complete line so this is not an issue.

The critical part is the writing of the FDF file. Different characters behave differently with different writing options so the user needs some control over these to ensure the output is right. The relevant options are `encoding` from `file` function and `useBytes` from `writeLines` function. These are now added as inputs to the `fill_pdf`. However R conventions are different than the old default values we had for both `encoding` and `useBytes` which makes the choice of a default option difficult. I have chosen to keep our old defaults for the sake of reverse compatibility and it seems to produce the largest set of characters that pdftk can actually write. **Note: Here I need confirmation from @pridiltal that the default inputs are ok**

Users will have to play around with these options to make sure the characters they want to write are writable. For instance I was simply unable to write "Ñ, ñ, É, Í, Ó" and "½ ¾ → ‘ ’ ” “ •" into the fields of the same file using a single set of options and even when using the right options for "½ ¾ → ‘ ’ ” “ •" to write to the file correctly, the output PDF actually ends up having malformed input fields. At this point this is probably a an issue that pdftk was not designed to handle. On my own code I have an array of string replacements to replace some weird characters with "close enough" characters but this is not a scalable option. Currently the package does not have a way of handling such characters. Current best practice is to use the default options as long as they work. If one comes across issues some of them can be solved by changing the file writing options. There doesn't seem to be a silver bullet to write all characters into the same file and in fact no way of writing some characters into a file.

**Also note: Travis seems to be having some problems today. Tests do pass on my machine but we might as well wait a bit**

### CODE REVIEW

**Comment by oganm** [comment]
The difference between names seem to be UTF 8 vs UTF 16 encoding. I am still unsure how to get from one from the other

½
UTF-8 Encoding: | 0xC2 0xBD
UTF-16 Encoding: | 0x00BD

https://stackoverflow.com/questions/55583644/convert-utf-8-encoding-in-text-form-to-characters

**Comment by oganm** [comment]
Thanks to the SO question, I now have a way of converting the codes into characters. However conversion is problematic because someone can name their field "#C2#BD" for whatever reason and get annoyed when they get ½ on the name. `pdftk` does not place escape characters around things that look like encoded characters. A possible solution is to have an option to enable-disable name conversion so that there are no surprises

**Comment by oganm** [comment]
Test file needs modification. due to testing weird characters it now can't be properly read in windows. Interestingly they aren't properly read in the same way the pdftk can't properly read those characters so examining that could lead to a fix

~~Note to self: create one or more test pdfs so changes to one test doesn't effect others~~

**Comment by pridiltal** [comment]
This is very useful @oganm.  Yes I am fine with the default input.  Please feel free to do the necessary changes  when you have time  and  push to the main branch. 

How about throwing a message when using the argument 'convert_field_names' with possible issues that could arise due to the use of pdftk.  (you have already explained it under the parameter description)

**Comment by oganm** [comment]
Note to self: tests with emoji, consider adding autocleanup code based on chosen encoding, possibly `iconv` or `gsub` or `stringri::stri_trans_general`.

**Comment by oganm** [comment]
Related issue and repository jkraemer/pdf-forms#53

**Comment by oganm** [comment]
This explains so many things...

https://stackoverflow.com/questions/56123130/how-to-read-a-file-with-unknown-encoding#56123130

FDF files do not use a single encoding. Which means if I simply use latin1 to read and to write

1. I can't read the file correctly in all places
2. I can't write some characters at all.

The issue is, most of the file is in latin1 and should remain in latin1, but certain characters require using UTF-16 encoding right in the middle of the file. If a field includes character that cannot be encoded by latin1, it will switch to UTF-16 just for that field. Current plan is:

- Read the FDF file as before. The field inputs cannot be correctly read at all times but that doesn't matter. We only care about latin1 encoded sections when reading this part.
- Find a way to create the new FDF file using mixed encoding. This will probably involve a combination of `charToRaw` `writeBin` or possibly `write` with `append`. Not sure what the options are in this regard. 

This also means the original plan of having users chose an encoding is out of the picture

The code below returns the correct encoding. Just need to make sure the input is UTF-8 which appears to be the default in most cases. need to see what can go wrong. maybe leave it at unknown or add that as an argument
```r
iconv('þ ¾ → ‘ ’ ” “ •',"UTF-8","UTF-16BE",toRaw = TRUE)
```

For the rest of the file

```r
iconv(%âãÏÓ",from = 'UTF-8',to='latin1',toRaw = TRUE)
```

~~does the job. Stitch them together and it's done.~~

In the middle of UTF-16 encoded data, you can have UTF-8 encoded ( ) and \ since those are escaped. The way it escapes them is to add a UTF-16 \ (00 5c) then add a UTF-8 encoded escaped character (28 instead of 00 28)

This forced me to build a very hacky solution where I encode every character one by one, manually code the escape characters to match the expected encoding. I expected some noticable slowdown but doesn't seem to matter all that much. Will be looking into this further. I expect there to be a standard way to do this that I don't know about yet. Though it is possible that this is unique to the FDF files. I googled "00 5c 28" which is the weird way "\\(" is encoded and I only found [this person](https://groups.google.com/forum/#!topic/bbedit/TqbmldXziYM) complaining about FDF files.

I actually started skimming through the [PDF file specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) but wasn't able to find an explanation for this. Though looking into the file, it is apparent that I should have done this earlier. So much useful stuff...

At a surface level, this PR is complete. I will look into the performance loss and test some possible edge cases and merge when complete

**Pull request merged**
